language: c
os:
  - linux
  - osx
env:
  - CONFIGURE_FLAGS=
  - CONFIGURE_FLAGS=--enable-sharedlibgbs
matrix:
  exclude:
    - os: osx
      compiler: gcc
addons:
  apt:
    packages:
      - libasound2-dev
      - libpulse-dev
      - libaudio-dev
compiler:
  - clang
  - gcc
