language: c
os:
  - linux
  - osx
env:
  - CONFIGURE_FLAGS=
  - CONFIGURE_FLAGS=--enable-sharedlibgbs
script:
  - ./configure && make && make test
  - make distclean
  - make dist
matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: CONFIGURE_FLAGS=--enable-sharedlibgbs
addons:
  apt:
    packages:
      - libasound2-dev
      - libpulse-dev
      - libaudio-dev
compiler:
  - clang
  - gcc
after_success:
  - bash <(curl -s https://codecov.io/bash)
