# This workflow will build and test gbsplay in various configurations on various systems.

name: Build and Test

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build-linux:
    name: Build and test under Linux

    needs: build-windows

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        flags: ['', --disable-i18n, --disable-zlib, --enable-sharedlibgbs]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install libasound2-dev libpulse-dev libaudio-dev
    - name: Build and test
      env:
        CC: ${{ matrix.compiler }}
        CONFIGURE_FLAGS: ${{ matrix.flags }}
      run: |
        make

  build-macos:
    name: Build and test under macOS

    needs: build-windows

    runs-on: macos-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        flags: ['', '--disable-i18n --disable-zlib']

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      env:
        CC: ${{ matrix.compiler }}
        CONFIGURE_FLAGS: ${{ matrix.flags }}
      run: |
        make

  build-windows:
    name: Build and test under Windows

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        flags: ['', --disable-i18n, --disable-zlib, --enable-sharedlibgbs, --disable-hardening]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        install: git base-devel ${{ matrix.compiler }}
        release: false
        update: false
    - name: Build and test
      env:
        CONFIGURE_FLAGS: ${{ matrix.flags }}
      run: |
        make
