# This workflow will build and test gbsplay in various configurations on various systems.

name: Build and Test

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build-linux:
    name: Build and test under Linux

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        flags: ['', --disable-i18n, --disable-zlib, --enable-sharedlibgbs]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install libasound2-dev libpulse-dev libaudio-dev
    - name: Build and test
      env:
        CC: ${{ matrix.compiler }}
        CONFIGURE_FLAGS: ${{ matrix.flags }}
      run: |
        make

  build-macos:
    name: Build and test under macOS

    runs-on: macos-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        flags: ['', '--disable-i18n --disable-zlib']

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      env:
        CC: ${{ matrix.compiler }}
        CONFIGURE_FLAGS: ${{ matrix.flags }}
      run: |
        make
